# Generated by Django 3.0.8 on 2020-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'default_permissions': ()},
        ),
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together={('name', 'director')},
        ),
    ]
